In [201]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from implementations import *
from proj1_helpers import *
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


**Test of regular training functions**

In [202]:
nsamples = 10000
nfeatures = 30
seed = 20
std = 10
y,tx,w = generate_bin_data(nsamples,nfeatures,seed,std)
loss = compute_loss(y,tx,w,"log")

In [212]:
print(loss)
print(w)

0.5012952747603642
[[ 0.00717422]
 [ 0.00308865]
 [ 0.0582141 ]
 [ 0.27696333]
 [-0.17971938]
 [ 0.0425894 ]
 [-0.14586581]
 [-0.14147049]
 [ 0.07732134]
 [-0.09432046]
 [ 0.05137078]
 [ 0.02031092]
 [ 0.19738013]
 [-0.10525107]
 [-0.26002759]
 [ 0.12185483]
 [ 0.01757635]
 [ 0.00668208]
 [-0.0165337 ]
 [-0.02090843]
 [ 0.13017959]
 [ 0.21173279]
 [ 0.04406918]
 [-0.19084252]
 [-0.02495173]
 [ 0.02195592]
 [ 0.08183416]
 [-0.0114103 ]
 [-0.03237466]
 [-0.02800488]
 [ 0.21003603]]


In [213]:
initial_w = np.zeros([nfeatures+1,1])
max_iters = 100000
gamma = 0.1

Least squares GD

In [214]:
w,loss = least_squares_GD(y,tx,initial_w,max_iters,gamma)

Terminated least_squares_GD after  39  iterations.


In [215]:
print(compute_loss(y, tx, w,'log'))
print(w)

0.42600000000000005
[[ 0.01948995]
 [ 0.02456619]
 [ 0.02384497]
 [ 0.02664302]
 [-0.0215254 ]
 [ 0.02779789]
 [-0.01526285]
 [-0.0026715 ]
 [ 0.00647283]
 [ 0.00428793]
 [-0.01536755]
 [ 0.03286872]
 [ 0.01100188]
 [ 0.00718382]
 [ 0.01737133]
 [-0.01404297]
 [ 0.00380908]
 [ 0.01668883]
 [-0.00192869]
 [-0.01563546]
 [ 0.03163693]
 [ 0.02928474]
 [ 0.01282253]
 [-0.00730779]
 [ 0.0325552 ]
 [-0.00543606]
 [ 0.02282659]
 [ 0.03377175]
 [-0.005536  ]
 [-0.00769299]
 [ 0.00359258]]


Least squares SGD

In [217]:
w,loss = least_squares_SGD(y,tx,initial_w,10000,gamma)

10000


In [218]:
print(compute_loss(y, tx, w,'log'))
print(w)

0.44660000000000005
[[ 0.00717422]
 [ 0.00308865]
 [ 0.0582141 ]
 [ 0.27696333]
 [-0.17971938]
 [ 0.0425894 ]
 [-0.14586581]
 [-0.14147049]
 [ 0.07732134]
 [-0.09432046]
 [ 0.05137078]
 [ 0.02031092]
 [ 0.19738013]
 [-0.10525107]
 [-0.26002759]
 [ 0.12185483]
 [ 0.01757635]
 [ 0.00668208]
 [-0.0165337 ]
 [-0.02090843]
 [ 0.13017959]
 [ 0.21173279]
 [ 0.04406918]
 [-0.19084252]
 [-0.02495173]
 [ 0.02195592]
 [ 0.08183416]
 [-0.0114103 ]
 [-0.03237466]
 [-0.02800488]
 [ 0.21003603]]


Least squares

In [220]:
w,loss = least_squares(y, tx)

In [221]:
print(compute_loss(y, tx, w,'log'))
print(w)

0.42290000000000005
[[ 0.07015639]
 [ 0.06372914]
 [ 0.06013928]
 [ 0.07101717]
 [-0.10098996]
 [ 0.0763126 ]
 [-0.07754896]
 [-0.03291536]
 [-0.00079236]
 [-0.0071469 ]
 [-0.08064651]
 [ 0.08854572]
 [ 0.0103884 ]
 [ 0.00294157]
 [ 0.03200131]
 [-0.0777082 ]
 [-0.01288403]
 [ 0.03699261]
 [-0.03312778]
 [-0.07448259]
 [ 0.08440702]
 [ 0.07952506]
 [ 0.01994368]
 [-0.05359551]
 [ 0.08904088]
 [-0.04645924]
 [ 0.05480948]
 [ 0.09362449]
 [-0.04184579]
 [-0.04943087]
 [-0.01506491]]


Ridge regression

In [251]:
lambda_ = 1

In [252]:
w,loss = ridge_regression(y, tx, lambda_)

In [253]:
print(compute_loss(y, tx, w,'log'))
print(w)

0.42600000000000005
[[7.39968373e-07]
 [3.91184103e-07]
 [3.91951551e-07]
 [3.97755616e-07]
 [3.26643641e-07]
 [3.99846319e-07]
 [3.37498315e-07]
 [3.56610884e-07]
 [3.68849866e-07]
 [3.64955392e-07]
 [3.41023574e-07]
 [4.05693281e-07]
 [3.78187229e-07]
 [3.68683775e-07]
 [3.87184711e-07]
 [3.41481894e-07]
 [3.65162822e-07]
 [3.86627281e-07]
 [3.61408716e-07]
 [3.36310326e-07]
 [4.03654931e-07]
 [4.03101216e-07]
 [3.81111576e-07]
 [3.49676474e-07]
 [4.06187141e-07]
 [3.49720752e-07]
 [3.93616502e-07]
 [4.07833347e-07]
 [3.50261746e-07]
 [3.48643492e-07]
 [3.63376899e-07]]


**Test of Logistic Regression on actual data**

In [159]:
path_tr = "../data/train.csv"
yb_tr, data_tr, ids_tr = load_csv_data(path_tr,True)

In [161]:
data_tr0, mean_tr, std_tr = standardize(data_tr)
data_tr0 = add_constant(data_tr0)

In [162]:
nfeatures = data_tr0.shape[1]
initial_w = np.ones([nfeatures,1])/nfeatures

Since the features can have numeric values in whatever range, $exp(X^\top\,w)$ can be very large when chosing $w_{initial}=1$ (or any other finite value), resulting in $\sigma=1$. On the other hand chosing $w_{initial}=0$ results in $\sigma=0.5$.
Not sure though whether that actually has an influence on the stability of the method.
On a second thought, standardisation or normalisation would actually make it reasonable to use a finite $w_{initial}$. I was thinking maybe $w_{initial} = \tfrac{1}{\# features}$.

In [165]:
w, loss = logistic_regression(yb_tr,data_tr0,initial_w,max_iters,0.2)

In [166]:
print(loss)
print(w)

7521493176.046137
[[-5.05269220e+07]
 [ 1.44569457e+07]
 [-1.77344108e+07]
 [-1.78444753e+06]
 [ 4.76387045e+06]
 [ 6.00179115e+05]
 [ 3.17657476e+06]
 [ 5.34524662e+05]
 [ 6.66779748e+06]
 [-1.60473116e+06]
 [ 8.65432603e+05]
 [-6.28674434e+06]
 [ 1.14619961e+07]
 [ 5.82217945e+05]
 [ 7.19960565e+06]
 [ 9.84034661e+05]
 [-5.83622605e+05]
 [ 7.26931178e+05]
 [ 1.35993151e+06]
 [ 1.14614161e+06]
 [-2.85887569e+06]
 [-7.04733140e+04]
 [ 3.12375671e+04]
 [ 1.41371656e+05]
 [ 4.13398084e+06]
 [ 4.12006185e+06]
 [ 4.12761988e+06]
 [ 3.97286141e+05]
 [ 5.77656952e+05]
 [ 5.73510469e+05]
 [-6.47081572e+05]]


In [174]:
w, loss = reg_logistic_regression(yb_tr,data_tr0,1+4,initial_w,max_iters,0.2)

In [176]:
print(loss)
print(w)

3994036.357120069
[[-667.99534162]
 [ 129.6766822 ]
 [-228.66895501]
 [ -14.94019797]
 [ -82.44496554]
 [-270.10833093]
 [-207.94622662]
 [-271.13099738]
 [ 143.39873142]
 [-125.98049701]
 [-168.71453466]
 [-183.56434577]
 [  85.82721938]
 [-270.38204073]
 [ 106.60059948]
 [  26.15895072]
 [ -16.03729886]
 [-112.25572516]
 [  30.03502361]
 [  16.39320674]
 [-128.22769493]
 [   4.9357043 ]
 [-165.3115051 ]
 [-238.13357031]
 [ -98.25480609]
 [ -91.23495215]
 [ -91.20886192]
 [-271.05084782]
 [-270.44408328]
 [-270.51287909]
 [-195.23694477]]


In [27]:
path_te = "../data/train.csv"
yb_te, data_te, ids_te = load_csv_data(path_te,True)

- log_reg working correctly?
- stochastic approach?
- iterations end conditions?
- preprocessing? (use all features?)
- ...?

TODO:
- bias_variance_decomposition
- cross_validation
- again test all methods
- prepare script run.py

TEST:

Required Functions

- logistic_regression
- reg_logistic_regression

Trainers

- my_least_squares_GD
- my_least_squares_SGD
- my_least_squares
- my_ridge_regression
- my_logistic_regression
- my_reg_logistic_regression
- my_stoch_logistic_regression

Utility functions for trainers

- compute_gradient
- compute_sigma
- batch_iter

Loss functions

- compute_loss

Preprocessing

- standardize
- split_data
- add_constant
- poly_expansion

Utility

- generate_data
- generate_bin_data
- column_array
- compute_y