In [2]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from implementations import *
from proj1_helpers import *
%load_ext autoreload
%autoreload 2

**Test of regular training functions**

In [3]:
nsamples = 1000
nfeatures = 20
seed = 20
std = 0.1
y,tx,w = generate_data(nsamples,nfeatures,seed,std)
loss = compute_loss(y,tx,w)

In [148]:
print(loss)
print(w)

0.005309625925735089
[[0.5881308 ]
 [0.89771373]
 [0.89153073]
 [0.81583748]
 [0.03588959]
 [0.69175758]
 [0.37868094]
 [0.51851095]
 [0.65795147]
 [0.19385022]
 [0.2723164 ]
 [0.71860593]
 [0.78300361]
 [0.85032764]
 [0.77524489]
 [0.03666431]
 [0.11669374]
 [0.7512807 ]
 [0.23921822]
 [0.25480601]
 [0.85762553]]


In [149]:
initial_w = np.zeros([nfeatures+1,1])
max_iters = 100000
gamma = 0.1

Least squares GD

In [150]:
w,loss = least_squares_GD(y,tx,initial_w,max_iters,gamma)

Terminated least_squares_GD after  539  iterations.


In [151]:
print(loss)
print(w)

0.005425532128798946
[[0.76351622]
 [0.86461981]
 [0.87597689]
 [0.80442434]
 [0.01378407]
 [0.67489353]
 [0.37532809]
 [0.51254593]
 [0.64790447]
 [0.17423959]
 [0.24771655]
 [0.69866241]
 [0.75143508]
 [0.84633841]
 [0.75840143]
 [0.01782753]
 [0.11286285]
 [0.71495562]
 [0.22391709]
 [0.2450083 ]
 [0.83532526]]


Least squares SGD

In [152]:
w,loss = least_squares_SGD(y,tx,initial_w,10000,gamma)

1000
Terminated least_squares_SGD after  1099  iterations.


In [153]:
print(loss)
print(w)

0.00588249800753959
[[0.69050174]
 [0.8718239 ]
 [0.89210358]
 [0.81019568]
 [0.00622989]
 [0.67833821]
 [0.39794494]
 [0.52490717]
 [0.65594455]
 [0.17459873]
 [0.26796299]
 [0.71413236]
 [0.75884473]
 [0.85811   ]
 [0.77840507]
 [0.02014027]
 [0.13195498]
 [0.72757485]
 [0.23740862]
 [0.24642586]
 [0.85488967]]


Least squares

In [154]:
w,loss = least_squares(y, tx)

In [155]:
print(loss)
print(w)

0.005208633401473409
[[0.61337157]
 [0.88092768]
 [0.89584667]
 [0.82287565]
 [0.02268107]
 [0.69495938]
 [0.39151281]
 [0.52983978]
 [0.65975028]
 [0.18017287]
 [0.25853949]
 [0.7189675 ]
 [0.76643704]
 [0.86417657]
 [0.77688533]
 [0.02612297]
 [0.12626421]
 [0.73099478]
 [0.23291732]
 [0.25594072]
 [0.8552125 ]]


Ridge regression

In [156]:
lambda_ = 0.0001

In [157]:
w,loss = ridge_regression(y, tx, lambda_)

In [158]:
print(loss)
print(w)

0.0053476111657850675
[[0.73418033]
 [0.87097238]
 [0.88401736]
 [0.81170066]
 [0.00987004]
 [0.68130856]
 [0.37964646]
 [0.5169666 ]
 [0.64658915]
 [0.17021278]
 [0.24472411]
 [0.70692478]
 [0.75758758]
 [0.85243436]
 [0.76433065]
 [0.011916  ]
 [0.11194507]
 [0.71799469]
 [0.22167696]
 [0.24292179]
 [0.8421676 ]]


**Test of Logistic Regression on actual data**

In [63]:
path_tr = "../data/train.csv"
yb_tr, data_tr, ids_tr = load_csv_data(path_tr,True)

In [69]:
data_tr0, mean_tr, std_tr = standardize(data_tr)
data_tr0 = add_constant(data_tr0)

In [70]:
nfeatures = data_tr0.shape[1]
initial_w = np.ones([nfeatures,1])/nfeatures

Since the features can have numeric values in whatever range, $exp(X^\top\,w)$ can be very large when chosing $w_{initial}=1$ (or any other finite value), resulting in $\sigma=1$. On the other hand chosing $w_{initial}=0$ results in $\sigma=0.5$.
Not sure though whether that actually has an influence on the stability of the method.
On a second thought, standardisation or normalisation would actually make it reasonable to use a finite $w_{initial}$. I was thinking maybe $w_{initial} = \tfrac{1}{\# features}$.

In [71]:
max_iters = 5000
w, loss = logistic_regression(yb_tr,data_tr0,initial_w,max_iters,0.2)

In [72]:
print(loss)
print(w)

0.2798
[[-2.52684145e+06]
 [ 7.22837053e+05]
 [-8.86942722e+05]
 [-8.91851537e+04]
 [ 2.38212051e+05]
 [ 3.00160112e+04]
 [ 1.58894333e+05]
 [ 2.67322358e+04]
 [ 3.33420963e+05]
 [-8.03067947e+04]
 [ 4.32986503e+04]
 [-3.14424400e+05]
 [ 5.73245164e+05]
 [ 2.91177055e+04]
 [ 3.60105593e+05]
 [ 4.92375251e+04]
 [-2.92017249e+04]
 [ 3.63261880e+04]
 [ 6.80401919e+04]
 [ 5.73310498e+04]
 [-1.42973964e+05]
 [-3.53037435e+03]
 [ 1.57540613e+03]
 [ 7.07173749e+03]
 [ 2.06721977e+05]
 [ 2.06028883e+05]
 [ 2.06406455e+05]
 [ 1.98739024e+04]
 [ 2.88896921e+04]
 [ 2.86823816e+04]
 [-3.23444273e+04]]


In [73]:
w = w/np.mean(w)
print(w)

[[ 1.16273904e+02]
 [-3.32617174e+01]
 [ 4.08131239e+01]
 [ 4.10390055e+00]
 [-1.09614496e+01]
 [-1.38120214e+00]
 [-7.31160414e+00]
 [-1.23009753e+00]
 [-1.53425365e+01]
 [ 3.69535831e+00]
 [-1.99240958e+00]
 [ 1.44683999e+01]
 [-2.63781700e+01]
 [-1.33986614e+00]
 [-1.65704434e+01]
 [-2.26568995e+00]
 [ 1.34373233e+00]
 [-1.67156816e+00]
 [-3.13090430e+00]
 [-2.63811763e+00]
 [ 6.57902024e+00]
 [ 1.62451985e-01]
 [-7.24931204e-02]
 [-3.25409625e-01]
 [-9.51241770e+00]
 [-9.48052464e+00]
 [-9.49789882e+00]
 [-9.14507804e-01]
 [-1.32937399e+00]
 [-1.31983449e+00]
 [ 1.48834540e+00]]


In [74]:
w, loss = reg_logistic_regression(yb_tr,data_tr0,1+4,initial_w,max_iters,0.2)

In [75]:
print(loss)
print(w)

0.6064
[[-667.99534162]
 [ 129.6766822 ]
 [-228.66895501]
 [ -14.94019797]
 [ -82.44496554]
 [-270.10833093]
 [-207.94622662]
 [-271.13099738]
 [ 143.39873142]
 [-125.98049701]
 [-168.71453466]
 [-183.56434577]
 [  85.82721938]
 [-270.38204073]
 [ 106.60059948]
 [  26.15895072]
 [ -16.03729886]
 [-112.25572516]
 [  30.03502361]
 [  16.39320674]
 [-128.22769493]
 [   4.9357043 ]
 [-165.3115051 ]
 [-238.13357031]
 [ -98.25480609]
 [ -91.23495215]
 [ -91.20886192]
 [-271.05084782]
 [-270.44408328]
 [-270.51287909]
 [-195.23694477]]


In [76]:
path_te = "../data/train.csv"
yb_te, data_te, ids_te = load_csv_data(path_te,True)
data_te0, mean_te, std_te = standardize(data_te)
data_te0 = add_constant(data_te0)

- log_reg working correctly?
- stochastic approach?
- iterations end conditions?
- preprocessing? (use all features?)
- ...?

TODO:
- bias_variance_decomposition
- cross_validation
- again test all methods
- prepare script run.py

TEST:

Required Functions

- logistic_regression
- reg_logistic_regression

Trainers

- my_least_squares_GD
- my_least_squares_SGD
- my_least_squares
- my_ridge_regression
- my_logistic_regression
- my_reg_logistic_regression
- my_stoch_logistic_regression

Utility functions for trainers

- compute_gradient
- compute_sigma
- batch_iter

Loss functions

- compute_loss

Preprocessing

- standardize
- split_data
- add_constant
- poly_expansion

Utility

- generate_data
- generate_bin_data
- column_array
- compute_y

In [130]:
path_tr = "../data/train.csv"
yb_tr, data_tr, ids_tr = load_csv_data(path_tr,False)
data_tr0, mean_tr, std_tr = standardize(data_tr)

In [131]:
degree = 3
data_tr0 = poly_expansion(data_tr0, degree, True, False)
nfeatures = data_tr0.shape[1]
initial_w = np.ones([nfeatures,1])/nfeatures

IndexError: index 30 is out of bounds for axis 1 with size 30

In [122]:
lambda_ = 0
w_SGD, loss_SGD = my_least_squares_SGD(yb_tr, data_tr0, initial_w, max_iters=10000, gamma=0.01, batch_size=4, lambda_=0, eps=1e-5)

250000


In [123]:
print(loss_SGD)
print(w_SGD)

0.25672
[[-0.33795112]
 [ 0.02825438]
 [-0.26895999]
 [-0.20370778]
 [-0.03479935]
 [-0.03064305]
 [ 0.39981581]
 [-0.04583121]
 [ 0.26990969]
 [-0.03119976]
 [-0.03830015]
 [-0.16818168]
 [ 0.09676256]
 [-0.0330539 ]
 [ 0.23968628]
 [-0.00848588]
 [ 0.04289482]
 [ 0.21914297]
 [ 0.03644386]
 [ 0.00884811]
 [ 0.07363898]
 [ 0.00458962]
 [-0.03605486]
 [-0.21872995]
 [ 0.02533292]
 [ 0.07259824]
 [ 0.07219765]
 [-0.00845207]
 [-0.03645911]
 [-0.03743925]
 [-0.14052943]]


In [124]:
path_te = "../data/test.csv"
yb_te, data_te, ids_te = load_csv_data(path_te,False)
data_te0, mean_te, std_te = standardize(data_te, mean_tr, std_tr)
data_te0 = add_constant(data_te0)
yb_te = yb_te.reshape(len(yb_te),1)
print(yb_te.shape)

(568238, 1)


In [125]:
y_pred = compute_y(data_te0, w_SGD)
print(y_pred.shape)

(568238, 1)


In [126]:
loss_gl = compute_loss(yb_te, data_te0, w_SGD, "log", lambda_=0)
print(loss_gl)

0.7474068964060834


In [127]:
create_csv_submission(ids_te, y_pred, "Testnumber2.csv")