In [146]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from implementations import *
from proj1_helpers import *
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


**Test of regular training functions**

In [147]:
nsamples = 1000
nfeatures = 20
seed = 20
std = 0.1
y,tx,w = generate_data(nsamples,nfeatures,seed,std)
loss = compute_loss(y,tx,w)

In [148]:
print(loss)
print(w)

0.005309625925735089
[[0.5881308 ]
 [0.89771373]
 [0.89153073]
 [0.81583748]
 [0.03588959]
 [0.69175758]
 [0.37868094]
 [0.51851095]
 [0.65795147]
 [0.19385022]
 [0.2723164 ]
 [0.71860593]
 [0.78300361]
 [0.85032764]
 [0.77524489]
 [0.03666431]
 [0.11669374]
 [0.7512807 ]
 [0.23921822]
 [0.25480601]
 [0.85762553]]


In [149]:
initial_w = np.zeros([nfeatures+1,1])
max_iters = 100000
gamma = 0.1

Least squares GD

In [150]:
w,loss = least_squares_GD(y,tx,initial_w,max_iters,gamma)

Terminated least_squares_GD after  539  iterations.


In [151]:
print(loss)
print(w)

0.005425532128798946
[[0.76351622]
 [0.86461981]
 [0.87597689]
 [0.80442434]
 [0.01378407]
 [0.67489353]
 [0.37532809]
 [0.51254593]
 [0.64790447]
 [0.17423959]
 [0.24771655]
 [0.69866241]
 [0.75143508]
 [0.84633841]
 [0.75840143]
 [0.01782753]
 [0.11286285]
 [0.71495562]
 [0.22391709]
 [0.2450083 ]
 [0.83532526]]


Least squares SGD

In [152]:
w,loss = least_squares_SGD(y,tx,initial_w,10000,gamma)

1000
Terminated least_squares_SGD after  1099  iterations.


In [153]:
print(loss)
print(w)

0.00588249800753959
[[0.69050174]
 [0.8718239 ]
 [0.89210358]
 [0.81019568]
 [0.00622989]
 [0.67833821]
 [0.39794494]
 [0.52490717]
 [0.65594455]
 [0.17459873]
 [0.26796299]
 [0.71413236]
 [0.75884473]
 [0.85811   ]
 [0.77840507]
 [0.02014027]
 [0.13195498]
 [0.72757485]
 [0.23740862]
 [0.24642586]
 [0.85488967]]


Least squares

In [154]:
w,loss = least_squares(y, tx)

In [155]:
print(loss)
print(w)

0.005208633401473409
[[0.61337157]
 [0.88092768]
 [0.89584667]
 [0.82287565]
 [0.02268107]
 [0.69495938]
 [0.39151281]
 [0.52983978]
 [0.65975028]
 [0.18017287]
 [0.25853949]
 [0.7189675 ]
 [0.76643704]
 [0.86417657]
 [0.77688533]
 [0.02612297]
 [0.12626421]
 [0.73099478]
 [0.23291732]
 [0.25594072]
 [0.8552125 ]]


Ridge regression

In [156]:
lambda_ = 0.0001

In [157]:
w,loss = ridge_regression(y, tx, lambda_)

In [158]:
print(loss)
print(w)

0.0053476111657850675
[[0.73418033]
 [0.87097238]
 [0.88401736]
 [0.81170066]
 [0.00987004]
 [0.68130856]
 [0.37964646]
 [0.5169666 ]
 [0.64658915]
 [0.17021278]
 [0.24472411]
 [0.70692478]
 [0.75758758]
 [0.85243436]
 [0.76433065]
 [0.011916  ]
 [0.11194507]
 [0.71799469]
 [0.22167696]
 [0.24292179]
 [0.8421676 ]]


**Test of Logistic Regression on actual data**

In [159]:
path_tr = "../data/train.csv"
yb_tr, data_tr, ids_tr = load_csv_data(path_tr,True)

In [161]:
data_tr0, mean_tr, std_tr = standardize(data_tr)
data_tr0 = add_constant(data_tr0)

In [162]:
nfeatures = data_tr0.shape[1]
initial_w = np.ones([nfeatures,1])/nfeatures

Since the features can have numeric values in whatever range, $exp(X^\top\,w)$ can be very large when chosing $w_{initial}=1$ (or any other finite value), resulting in $\sigma=1$. On the other hand chosing $w_{initial}=0$ results in $\sigma=0.5$.
Not sure though whether that actually has an influence on the stability of the method.
On a second thought, standardisation or normalisation would actually make it reasonable to use a finite $w_{initial}$. I was thinking maybe $w_{initial} = \tfrac{1}{\# features}$.

In [165]:
w, loss = logistic_regression(yb_tr,data_tr0,initial_w,max_iters,0.2)

In [166]:
print(loss)
print(w)

7521493176.046137
[[-5.05269220e+07]
 [ 1.44569457e+07]
 [-1.77344108e+07]
 [-1.78444753e+06]
 [ 4.76387045e+06]
 [ 6.00179115e+05]
 [ 3.17657476e+06]
 [ 5.34524662e+05]
 [ 6.66779748e+06]
 [-1.60473116e+06]
 [ 8.65432603e+05]
 [-6.28674434e+06]
 [ 1.14619961e+07]
 [ 5.82217945e+05]
 [ 7.19960565e+06]
 [ 9.84034661e+05]
 [-5.83622605e+05]
 [ 7.26931178e+05]
 [ 1.35993151e+06]
 [ 1.14614161e+06]
 [-2.85887569e+06]
 [-7.04733140e+04]
 [ 3.12375671e+04]
 [ 1.41371656e+05]
 [ 4.13398084e+06]
 [ 4.12006185e+06]
 [ 4.12761988e+06]
 [ 3.97286141e+05]
 [ 5.77656952e+05]
 [ 5.73510469e+05]
 [-6.47081572e+05]]


In [171]:
w, loss = reg_logistic_regression(yb_tr,data_tr0,1+4,initial_w,max_iters,0.2)

In [172]:
print(loss)
print(w)

5111627.2071659565
[[-667.99534162]
 [ 129.6766822 ]
 [-228.66895501]
 [ -14.94019797]
 [ -82.44496554]
 [-270.10833093]
 [-207.94622662]
 [-271.13099738]
 [ 143.39873142]
 [-125.98049701]
 [-168.71453466]
 [-183.56434577]
 [  85.82721938]
 [-270.38204073]
 [ 106.60059948]
 [  26.15895072]
 [ -16.03729886]
 [-112.25572516]
 [  30.03502361]
 [  16.39320674]
 [-128.22769493]
 [   4.9357043 ]
 [-165.3115051 ]
 [-238.13357031]
 [ -98.25480609]
 [ -91.23495215]
 [ -91.20886192]
 [-271.05084782]
 [-270.44408328]
 [-270.51287909]
 [-195.23694477]]


In [27]:
path_te = "../data/train.csv"
yb_te, data_te, ids_te = load_csv_data(path_te,True)

- log_reg working correctly?
- stochastic approach?
- iterations end conditions?
- preprocessing? (use all features?)
- ...?

TODO:
- bias_variance_decomposition
- cross_validation
- again test all methods
- prepare script run.py

TEST:

Required Functions

- logistic_regression
- reg_logistic_regression

Trainers

- my_least_squares_GD
- my_least_squares_SGD
- my_least_squares
- my_ridge_regression
- my_logistic_regression
- my_reg_logistic_regression
- my_stoch_logistic_regression

Utility functions for trainers

- compute_gradient
- compute_sigma
- batch_iter

Loss functions

- compute_loss

Preprocessing

- standardize
- split_data
- add_constant
- poly_expansion

Utility

- generate_data
- generate_bin_data
- column_array
- compute_y