In [131]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from implementations import *
from proj1_helpers import *
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


**Test of regular training functions**

In [72]:
nsamples = 1000
nfeatures = 20
seed = 20
std = 0.1
y,tx,w = generate_data(nsamples,nfeatures,seed,std)
loss = compute_loss(y,tx,w)

In [73]:
print(loss)
print(w)

0.005309625925735089
[[0.5881308 ]
 [0.89771373]
 [0.89153073]
 [0.81583748]
 [0.03588959]
 [0.69175758]
 [0.37868094]
 [0.51851095]
 [0.65795147]
 [0.19385022]
 [0.2723164 ]
 [0.71860593]
 [0.78300361]
 [0.85032764]
 [0.77524489]
 [0.03666431]
 [0.11669374]
 [0.7512807 ]
 [0.23921822]
 [0.25480601]
 [0.85762553]]


In [74]:
initial_w = np.zeros([nfeatures+1,1])
max_iters = 1000
gamma = 0.1

Least squares GD

In [75]:
w,loss = least_squares_GD(y,tx,initial_w,max_iters,gamma)

In [76]:
print(loss)
print(w)

0.0052593447826233585
[[0.6890661 ]
 [0.87512541]
 [0.88846579]
 [0.81566863]
 [0.01444484]
 [0.68646149]
 [0.38430377]
 [0.52174775]
 [0.65213307]
 [0.17469574]
 [0.24988232]
 [0.71191271]
 [0.76128226]
 [0.85666565]
 [0.76935158]
 [0.01784878]
 [0.11764169]
 [0.72330248]
 [0.2260221 ]
 [0.24789811]
 [0.84770479]]


Least squares SGD

In [77]:
batch_size = 5

In [78]:
w,loss = least_squares_SGD(y,tx,initial_w,max_iters,gamma,batch_size)

In [79]:
print(loss)
print(w)

0.005443839601445151
[[0.69255826]
 [0.87863503]
 [0.89415912]
 [0.82099462]
 [0.00597278]
 [0.68762262]
 [0.38623202]
 [0.51888116]
 [0.65084684]
 [0.17260222]
 [0.26018386]
 [0.70635302]
 [0.77162842]
 [0.86587718]
 [0.76683629]
 [0.02233551]
 [0.11459682]
 [0.72804092]
 [0.22694495]
 [0.23968123]
 [0.85211246]]


Least squares

In [80]:
w,loss = least_squares(y, tx)

In [81]:
print(loss)
print(w)

0.005208633401473409
[[0.61337157]
 [0.88092768]
 [0.89584667]
 [0.82287565]
 [0.02268107]
 [0.69495938]
 [0.39151281]
 [0.52983978]
 [0.65975028]
 [0.18017287]
 [0.25853949]
 [0.7189675 ]
 [0.76643704]
 [0.86417657]
 [0.77688533]
 [0.02612297]
 [0.12626421]
 [0.73099478]
 [0.23291732]
 [0.25594072]
 [0.8552125 ]]


Ridge regression

In [82]:
lambda_ = 0.1

In [83]:
w,loss = ridge_regression(y, tx, lambda_)

In [84]:
print(loss)
print(w)

0.06267882577209904
[[0.9142397 ]
 [0.58544917]
 [0.58923816]
 [0.57562004]
 [0.35012217]
 [0.52174881]
 [0.42938352]
 [0.48052005]
 [0.53178707]
 [0.3871863 ]
 [0.41844349]
 [0.51696615]
 [0.55292467]
 [0.59353327]
 [0.55153101]
 [0.33768782]
 [0.35578199]
 [0.54248559]
 [0.4066689 ]
 [0.41550889]
 [0.56563421]]


**Test of Logistic Regression on actual data**

In [144]:
path_tr = "../data/train.csv"
yb_tr, data_tr, ids_tr = load_csv_data(path_tr,True)

In [145]:
data_tr0, mean_tr, std_tr = standardize(data_tr)
data_tr0 = add_constant(data_tr0)

In [149]:
nfeatures = data_tr0.shape[1]
initial_w = np.ones([nfeatures,1])/nfeatures

Since the features can have numeric values in whatever range, $exp(X^\top\,w)$ can be very large when chosing $w_{initial}=1$ (or any other finite value), resulting in $\sigma=1$. On the other hand chosing $w_{initial}=0$ results in $\sigma=0.5$.
Not sure though whether that actually has an influence on the stability of the method.
On a second thought, standardisation or normalisation would actually make it reasonable to use a finite $w_{initial}$. I was thinking maybe $w_{initial} = \tfrac{1}{\# features}$.

In [212]:
w, loss = logistic_regression(yb_tr,data_tr0,initial_w,100,0.2,"log",100)

In [210]:
print(loss)
print(w)

182768983286.7879
[[ 1.78793754e+06]
 [-8.69719032e+05]
 [ 1.00520752e+06]
 [ 8.78916477e+04]
 [-2.83357305e+06]
 [-4.39036435e+06]
 [-4.15714124e+06]
 [-4.39033255e+06]
 [ 1.53953336e+06]
 [-1.22832531e+06]
 [-3.32933746e+06]
 [-1.81522155e+05]
 [-1.94786233e+06]
 [-4.39037307e+06]
 [-1.20876023e+06]
 [ 7.82743552e+04]
 [-3.06565505e+04]
 [-9.91318973e+05]
 [-7.64781161e+02]
 [-2.54748124e+04]
 [-1.62357394e+06]
 [-8.28203957e+04]
 [-3.06199166e+06]
 [-3.96192896e+06]
 [-2.74909754e+06]
 [-2.60591434e+06]
 [-2.60571145e+06]
 [-4.38727058e+06]
 [-4.39036084e+06]
 [-4.39036335e+06]
 [-3.41964447e+06]]


In [27]:
path_te = "../data/train.csv"
yb_te, data_te, ids_te = load_csv_data(path_te,True)

- log_reg working correctly?
- stochastic approach?
- iterations end conditions?
- preprocessing? (use all features?)
- ...?

TODO:
- bias_variance_decomposition
- cross_validation
- prepare script run.py
- stochastic version for log-reg
- implement end conditions for iterative methods