In [1]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from implementations import *
from proj1_helpers import *
%load_ext autoreload
%autoreload 2

import time

**Test of regular training functions**

In [14]:
nsamples = 50000
nfeatures = 30
seed = 20
std = 10
y,tx,w = generate_bin_data(nsamples,nfeatures,seed,std)
loss = compute_loss(y,tx,w,"log")

In [15]:
print(loss)
print(w)

0.4220400000000001
[[ 0.1762616 ]
 [ 0.79542746]
 [ 0.78306146]
 [ 0.63167495]
 [-0.92822083]
 [ 0.38351516]
 [-0.24263812]
 [ 0.03702189]
 [ 0.31590293]
 [-0.61229956]
 [-0.4553672 ]
 [ 0.43721187]
 [ 0.56600722]
 [ 0.70065528]
 [ 0.55048979]
 [-0.92667139]
 [-0.76661253]
 [ 0.5025614 ]
 [-0.52156357]
 [-0.49038797]
 [ 0.71525106]
 [ 0.89955805]
 [ 0.12337372]
 [-0.64243896]
 [ 0.54050387]
 [-0.01523792]
 [ 0.26250613]
 [ 0.67899585]
 [-0.07792121]
 [-0.00411985]
 [ 0.35882224]]


In [16]:
tx = tx[:,1:]

In [17]:
tx = poly_expansion(tx, 2, True, True)

In [20]:
print(tx.shape)
print(30*30+30+1)

(50000, 931)
931


In [21]:
initial_w = np.zeros([nfeatures+1,1])
max_iters = 1000
gamma = 0.1

Least squares GD

In [47]:
start = time.time()
w,loss = least_squares_GD(y,tx,initial_w,max_iters,gamma)
end = time.time()
print("Execution time = ",end-start,"s")

Terminated least_squares_GD after  139  iterations.
Execution time =  0.25521326065063477 s


In [48]:
print(compute_loss(y, tx, w,'log'))
print(w)

0.42292
[[ 7.56615789e-03]
 [ 1.51421797e-02]
 [ 5.17122978e-02]
 [ 2.92672558e-02]
 [-3.55065851e-02]
 [ 2.57122701e-02]
 [ 1.26466739e-02]
 [ 3.56001353e-05]
 [ 4.24455960e-02]
 [-1.74761305e-02]
 [-1.93680993e-02]
 [ 4.40545555e-02]
 [ 5.04882252e-02]
 [ 4.34375725e-02]
 [ 3.55263249e-02]
 [-5.77199818e-02]
 [-2.04646026e-02]
 [ 2.61935964e-02]
 [-3.45234978e-02]
 [-2.80410930e-02]
 [ 4.00575521e-02]
 [ 2.18675900e-02]
 [-6.46606878e-03]
 [-3.06811875e-02]
 [ 4.41382188e-02]
 [ 1.38209445e-02]
 [ 1.56440842e-02]
 [ 4.35599118e-02]
 [-1.17345926e-02]
 [-1.38353476e-02]
 [ 1.52771409e-02]]


Least squares SGD

In [51]:
start = time.time()
w,loss = least_squares_SGD(y,tx,initial_w,10000,gamma)
end = time.time()
print("Execution time = ",end-start,"s")

Terminated least_squares_SGD after  99  iterations.
Execution time =  0.019011974334716797 s


In [52]:
print(compute_loss(y, tx, w,'log'))
print(w)

0.42314
[[ 0.03276812]
 [-0.06433142]
 [ 0.03118197]
 [-0.09032684]
 [-0.01173774]
 [ 0.06006896]
 [ 0.04916534]
 [ 0.02334943]
 [ 0.03234766]
 [ 0.04796303]
 [-0.00117982]
 [ 0.09113767]
 [ 0.12663447]
 [-0.0273359 ]
 [ 0.12600499]
 [-0.05557246]
 [-0.00932897]
 [ 0.09243668]
 [ 0.04104187]
 [-0.12114585]
 [ 0.08308621]
 [ 0.10563868]
 [-0.04125099]
 [-0.04268297]
 [ 0.07773246]
 [-0.1394915 ]
 [ 0.01784272]
 [ 0.00464978]
 [ 0.01349729]
 [-0.03749372]
 [ 0.00515157]]


Least squares

In [53]:
start = time.time()
w,loss = least_squares(y, tx)
end = time.time()
print("Execution time = ",end-start,"s")

Execution time =  0.01906752586364746 s


In [54]:
print(compute_loss(y, tx, w,'log'))
print(w)

0.42124
[[-6.55115197e-02]
 [ 2.22668788e-02]
 [ 7.57476131e-02]
 [ 4.26000941e-02]
 [-5.16702434e-02]
 [ 3.77203864e-02]
 [ 1.91816700e-02]
 [ 5.72106217e-05]
 [ 6.16834646e-02]
 [-2.51878858e-02]
 [-2.74618360e-02]
 [ 6.39543641e-02]
 [ 7.33123155e-02]
 [ 6.28497662e-02]
 [ 5.15755950e-02]
 [-8.25583047e-02]
 [-2.88839680e-02]
 [ 3.87906215e-02]
 [-4.98191283e-02]
 [-4.03417582e-02]
 [ 5.91570080e-02]
 [ 3.23461396e-02]
 [-8.47448241e-03]
 [-4.36612646e-02]
 [ 6.39448350e-02]
 [ 1.97631116e-02]
 [ 2.28211852e-02]
 [ 6.36018330e-02]
 [-1.67636277e-02]
 [-1.99850431e-02]
 [ 2.34793873e-02]]


Ridge regression

In [55]:
lambda_ = 1

In [56]:
start = time.time()
w,loss = ridge_regression(y, tx, lambda_)
end = time.time()
print("Execution time = ",end-start,"s")

Execution time =  0.0067331790924072266 s


In [57]:
print(compute_loss(y, tx, w,'log'))
print(w)

0.4228200000000001
[[0.01428077]
 [0.00773409]
 [0.00981783]
 [0.0085559 ]
 [0.00479252]
 [0.00837662]
 [0.00758801]
 [0.00690233]
 [0.00932104]
 [0.00586043]
 [0.00575732]
 [0.00942371]
 [0.0098297 ]
 [0.00940767]
 [0.00892908]
 [0.00349308]
 [0.00569079]
 [0.00838318]
 [0.00489587]
 [0.00524245]
 [0.00916573]
 [0.00812286]
 [0.00645829]
 [0.00507424]
 [0.00944579]
 [0.00767406]
 [0.00778345]
 [0.00939163]
 [0.00619175]
 [0.00607977]
 [0.00769429]]


Logistic Regression

In [58]:
start = time.time()
w,loss = logistic_regression(y, tx, initial_w, max_iters, gamma)
end = time.time()
print("Execution time = ",end-start,"s")

Execution time =  2.1895809173583984 s


In [59]:
print(compute_loss(y, tx, w,'log'))
print(w)

0.4939200000000001
[[-4573.77696557]
 [  439.25031905]
 [ 1671.34528355]
 [  902.93049902]
 [-1269.94317535]
 [  803.15089722]
 [  373.26241927]
 [  -70.53323746]
 [ 1355.29055389]
 [ -657.1444643 ]
 [ -712.75213673]
 [ 1398.86852266]
 [ 1628.04472357]
 [ 1383.5564438 ]
 [ 1123.54929705]
 [-1971.64007251]
 [ -743.52890177]
 [  833.11272665]
 [-1227.31004297]
 [-1006.98932953]
 [ 1302.88278172]
 [  681.1808689 ]
 [ -270.21007863]
 [-1086.55376691]
 [ 1400.75694604]
 [  382.80052575]
 [  447.01736519]
 [ 1404.93351888]
 [ -456.49024192]
 [ -531.19463378]
 [  464.8728527 ]]


Regularized Logistic Regression

In [61]:
start = time.time()
w,loss = reg_logistic_regression(y, tx, lambda_ ,initial_w, max_iters, gamma)
end = time.time()
print("Execution time = ",end-start,"s")

Execution time =  2.2424869537353516 s


In [62]:
print(compute_loss(y, tx, w,'log'))
print(w)

0.57718
[[-873.22501765]
 [-349.43556253]
 [-176.83406141]
 [-281.40989336]
 [-586.72098916]
 [-302.73179968]
 [-364.9235337 ]
 [-422.94262943]
 [-219.81159121]
 [-505.95358578]
 [-515.54773856]
 [-212.41753803]
 [-185.2441843 ]
 [-217.33218187]
 [-253.59351433]
 [-695.34146281]
 [-520.76210891]
 [-300.25440617]
 [-587.32877586]
 [-555.71385282]
 [-233.94831363]
 [-318.55838798]
 [-452.9512098 ]
 [-568.3116537 ]
 [-213.09403698]
 [-354.85400829]
 [-348.33301964]
 [-216.25449162]
 [-477.06500134]
 [-488.55085603]
 [-350.28035759]]


Stochastic regularized Logistic Regression

In [70]:
batch_size = 10
start = time.time()
w,loss = my_stoch_logistic_regression(y, tx, initial_w, max_iters, gamma, batch_size, "log", lambda_=0, eps=1e-1)
end = time.time()
print("Execution time = ",end-start,"s")

Execution time =  2.3909947872161865 s


In [71]:
print(compute_loss(y, tx, w,'log'))
print(w)

0.4394
[[-416.00125638]
 [  51.89554091]
 [ 171.80413891]
 [  96.77935575]
 [-114.97461932]
 [  87.45372182]
 [  45.08978716]
 [   1.04649537]
 [ 140.87828362]
 [ -55.04976754]
 [ -60.52591295]
 [ 146.06546734]
 [ 167.08266243]
 [ 143.63526444]
 [ 117.62254721]
 [-184.70458772]
 [ -63.94035047]
 [  89.1775153 ]
 [-112.02517161]
 [ -90.27686405]
 [ 135.41394236]
 [  75.16661056]
 [ -17.63051165]
 [ -97.91227243]
 [ 145.59634985]
 [  46.18438208]
 [  52.48075721]
 [ 145.55430735]
 [ -35.96659224]
 [ -43.51156378]
 [  54.76533247]]


**Test of Logistic Regression on actual data**

In [77]:
path_tr = "../data/train.csv"
yb_tr, data_tr, ids_tr = load_csv_data(path_tr,False)

In [78]:
data_tr0, mean_tr, std_tr = standardize(data_tr)
data_tr0 = add_constant(data_tr0)

In [79]:
nfeatures = data_tr0.shape[1]
initial_w = np.ones([nfeatures,1])/nfeatures

Since the features can have numeric values in whatever range, $exp(X^\top\,w)$ can be very large when chosing $w_{initial}=1$ (or any other finite value), resulting in $\sigma=1$. On the other hand chosing $w_{initial}=0$ results in $\sigma=0.5$.
Not sure though whether that actually has an influence on the stability of the method.
On a second thought, standardisation or normalisation would actually make it reasonable to use a finite $w_{initial}$. I was thinking maybe $w_{initial} = \tfrac{1}{\# features}$.

In [80]:
w, loss = logistic_regression(yb_tr,data_tr0,initial_w,max_iters,0.2)

In [81]:
print(loss)
print(w)

0.2975199999999999
[[-2.33442832e+07]
 [ 7.94623610e+06]
 [-9.26840120e+06]
 [-9.56443613e+05]
 [ 2.45844934e+06]
 [ 1.12675666e+05]
 [ 1.90648523e+06]
 [ 7.63687507e+04]
 [ 3.67298270e+06]
 [-9.42630850e+05]
 [ 5.02813322e+05]
 [-3.79754805e+06]
 [ 5.20118195e+06]
 [ 1.02676813e+05]
 [ 3.27850623e+06]
 [-2.54173419e+04]
 [-9.88946817e+04]
 [-1.23959790e+05]
 [-6.14737109e+03]
 [ 4.42328464e+04]
 [-1.43877942e+06]
 [ 8.45614235e+04]
 [ 1.66554932e+05]
 [-2.70457162e+05]
 [ 1.31175150e+06]
 [ 1.27529404e+06]
 [ 1.27549556e+06]
 [ 5.15947235e+04]
 [ 9.98707569e+04]
 [ 9.96238520e+04]
 [-1.28187363e+05]]


In [84]:
w, loss = reg_logistic_regression(yb_tr,data_tr0,1,initial_w,max_iters,0.2)

In [85]:
print(loss)
print(w)

0.31354799999999994
[[-1.22676709e+05]
 [ 3.74880448e+04]
 [-4.69533429e+04]
 [-3.27429318e+03]
 [ 1.02134583e+04]
 [-3.83339757e+03]
 [ 7.13302459e+03]
 [-4.04353031e+03]
 [ 1.96412098e+04]
 [-9.36516805e+03]
 [-2.90433059e+02]
 [-2.39592936e+04]
 [ 2.44817466e+04]
 [-3.89141842e+03]
 [ 2.13530628e+04]
 [-2.93264029e+02]
 [-6.19251874e+02]
 [-3.49767635e+03]
 [-7.49404688e+01]
 [ 4.34500428e+02]
 [-8.32906499e+03]
 [ 4.99690353e+02]
 [-2.12980571e+03]
 [-6.07101449e+03]
 [ 4.45896342e+03]
 [ 4.38184919e+03]
 [ 4.38167909e+03]
 [-4.15334004e+03]
 [-3.90730062e+03]
 [-3.90883202e+03]
 [-4.43801773e+03]]


TODO:
- bias_variance_decomposition
- cross_validation
- again test all methods
- prepare script run.py
- optimize end condition log reg

TEST:

Trainers

- my_least_squares_GD
- my_least_squares_SGD
- my_least_squares
- my_ridge_regression
- my_logistic_regression
- my_reg_logistic_regression
- my_stoch_logistic_regression

Utility functions for trainers

- compute_gradient
- compute_sigma
- batch_iter

Loss functions

- compute_loss