In [73]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from implementations import *
from proj1_helpers import *
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [74]:
y, tx, w_actual = generate_data(100,1,1)
loss_actual = compute_loss(y,tx,w_actual)
print(loss_actual)

0.09675526170705176


In [75]:
loss_gd, w_gd = gradient_descent(y,tx,w_actual*0,100,1)
loss_sgd, w_sgd = stochastic_gradient_descent(y,tx,w_actual*0,1,100,.4)
loss_ls, w_ls = least_squares(y,tx)
loss_rr, w_rr = ridge_regression(y,tx,0)

In [76]:
print(loss_gd)
print(w_gd)
print()
print(loss_sgd)
print(w_sgd)
print()
print(loss_ls)
print(w_ls)
print()
print(loss_rr)
print(w_rr)

[[0.5288682 ]
 [0.59138125]]
0.09481188517356266

[[1.00819058]
 [0.88814521]]
0.29247307771363884

[[0.52876677]
 [0.59157675]]
0.09481188349911082

[[0.52876677]
 [0.59157675]]
0.09481188349911082
